apiVersion: v2
name: microservices
description: A Helm chart for microservices (user-service, product-service, order-service)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - fastapi
  - python
maintainers:
  - name: Chen Yuxiang




