apiVersion: v2
name: observability-platform
description: A Helm chart for observability platform (Prometheus, Grafana, Loki, Jaeger)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - observability
  - monitoring
  - logging
  - tracing
  - prometheus
  - grafana
  - loki
  - jaeger
maintainers:
  - name: Chen Yuxiang

dependencies:
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 5.0.0
  - name: jaeger
    repository: https://jaegertracing.github.io/helm-charts
    version: 0.71.0


